[workspace]
resolver = "2"
members = [
    "crates/*",
    "ui-backend",
    "energy-simulator",
    "manager",
    "sensor-data/ingestor",
    "sensor-data/generator",
    "sensor-data/crates/parser",
]
